development:
  cloud_name: onuhenry
  api_key: '584885673446888'
  api_secret: UL3xdFcNwvlKsIrZoJn-ehpne2Y
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: onuhenry
  api_key: '584885673446888'
  api_secret: UL3xdFcNwvlKsIrZoJn-ehpne2Y
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: onuhenry
  api_key: '584885673446888'
  api_secret: UL3xdFcNwvlKsIrZoJn-ehpne2Y
  enhance_image_tag: true
  static_file_support: false