development:
  cloud_name: onuhenry
  api_key: <%= Rails.application.credentials.cloudinary[:api_key]%>
  api_secret: <%= Rails.application.credentials.cloudinary[:api_secret]%>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: onuhenry
  api_key: <%= Rails.application.credentials.cloudinary[:api_key]%>
  api_secret: <%= Rails.application.credentials.cloudinary[:api_secret]%>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: onuhenry
  api_key: <%= Rails.application.credentials.cloudinary[:api_key]%>
  api_secret: <%= Rails.application.credentials.cloudinary[:api_secret]%>
  enhance_image_tag: true
  static_file_support: false